# Generated by Django 4.0.6 on 2022-07-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_delete_product'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='store',
            managers=[
            ],
        ),
    ]
