# Generated by Django 4.0.6 on 2022-07-28 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_store_managers'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
            preserve_default=False,
        ),
    ]
