# Generated by Django 4.0.6 on 2022-07-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_state',
            field=models.CharField(blank=True, choices=[('CANCELED', 'CANCELED'), ('DELIVERED', 'DELIVERED')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='order.orderproduct'),
        ),
    ]
